import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeSwitcher } from "nextjs-themes";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Tailwind CSS Example",
  description: "Generated by Mayank <https://github.com/mayank1513>",
};

/** Layout */
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeSwitcher />
        {children}
      </body>
    </html>
  );
}
